---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2scoped
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1b
reclaimPolicy: Retain
mountOptions:
  - debug
